name: Hidden treasures
favicon: null
layout_spectrum: 0.12492198380641639
typography_spectrum: 0.27870786958374083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.027510860236361623
  lightness: 0.8356623819563538
  saturation: 0.733481370145455
  rhythmicContrast: 0.7793089654296637
purpose: []
